package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/wxshope/go-admin Begin; DO NOT EDIT.

	// Code generated by github.com/wxshope/go-admin End; DO NOT EDIT.
}

